FROM python:3.11.9-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update \
    && apt-get -y install ncat gcc postgresql \
    && apt-get clean

RUN pip install --upgrade pip
RUN pip install uv
COPY ./requirements ./requirements
RUN uv pip install -r ./requirements/requirements.dev.txt --system

COPY . .

ENTRYPOINT [ "bash", "docker/api/entrypoint.sh" ]
