services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile.dev
    command: fastapi dev api/main.py --host 0.0.0.0
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    command: [ "postgres", "-c", "log_statement=all" ]
    environment:
      POSTGRES_DB: develop
      POSTGRES_USER: develop
      POSTGRES_PASSWORD: develop
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
